### ISSUE TITLE
Upload plugin allows image to cover the toolbar

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-upload#33]
## Steps to reproduce
1. Open editor with the upload plugin and an image.
2. Make the editor scrollable.
3. Focus the editor and scroll down.

## Current result
Image covers a toolbar.

## Notes
I checked this issue twice - on the editor with plugin and without it. This bug is reproducable only if upload plugin is loaded. I belive it messes something with z-index, when I increased it for a toolbar, everything was fine.

## Screenshot
![screen](https://user-images.githubusercontent.com/20988892/26976436-1ad49378-4d24-11e7-9bff-fd2f54644699.png)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
This is triggered by the following `imageuploadprogress.scss` lines (position to be precise):

```scss
figure.image {
	position: relative;
	overflow: hidden;
}
```

But I wonder whether the issue isn't really caused by too low `z-index` of the balloonpanel (or something).

**Comment by Reinmar** [comment]
I think we'll have to first resolve https://github.com/ckeditor/ckeditor5-ui/issues/218.

**Comment by oleq** [comment]
I found out this is an issue of editor-classic only because other implementations use `BalloonPanelView` that has proper `z-index`. I decided to put [the fix](https://github.com/ckeditor/ckeditor5-editor-classic/issues/63) in the editor-classic instead of `StickyToolbarView` to keep the component as generic as possible.

And it has pretty much nothing to do with https://github.com/ckeditor/ckeditor5-ui/issues/218 😌
