### ISSUE TITLE
FileRepository doesnt catch reject of promise

### ISSUE THREAD

**Issue by Maqsyo** [ckeditor/ckeditor5-upload#91]
If I'm rejecting the upload-promise, there will be an alert of the ui-notifications. I couldn't find out how to catch this reject
![image](https://user-images.githubusercontent.com/19644698/53343819-87f94b80-3911-11e9-8a90-960b651b032a.png)

i hope you could help me

**Comment by f1ames** [comment]
The fact that you are rejecting the promise with error causes notification to show. The code responsible for this behaviour is located in `ckeditor5-image` plugin - https://github.com/ckeditor/ckeditor5-image/blob/1f4e70de43a34de42f67976c8c9b8bc868337924/src/imageupload/imageuploadediting.js#L213-L226.

So if this promise is rejected with an error which has a message the message will be displayed in notification. You can work around this by providing empty message, but then it will be good to have some other indication in the UI that uploading failed so users don't get confused.

---

@Maqsyo, please remember that this is a place for reporting issues and features requests. When looking for any clarifications or asking questions about the API/code you may first refer to our docs ([API](https://ckeditor.com/docs/ckeditor5/latest/api/index.html) or [upload adapters deep dive](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html)) or try asking on [CKEditor 5 gitter channel](https://gitter.im/ckeditor/ckeditor5) or [StackOverflow](https://stackoverflow.com/questions/tagged/ckeditor5).

**Comment by Maqsyo** [comment]
I'm sorry, but this is, in fact, not true..
If i doesn't pass a string, an alert occurs with the text "undefined"
If i pass `false` an alert occurs with "false".
The alert comes from the notification-plugin, which i haven't enabled. And this clearly says, that this alert is only fired, if an error wont be catched before.

For the error i have an own toast-system which shows the error.

Do i have to set the loader-state to error before i'm calling `reject` ?

In your provided example there is only passed a string to the reject function. I couldn't find anything to prevent the alert..

Thank you anyway

**Comment by Maqsyo** [comment]
![image](https://user-images.githubusercontent.com/19644698/53397569-b9bcf180-39a7-11e9-821d-a3b1fb6345d9.png)

It does work if i set the loader.status to 'aborted'
Would be great if you could add this to your example...

**Comment by f1ames** [comment]
> I'm sorry, but this is, in fact, not true..
> If i doesn't pass a string, an alert occurs with the text "undefined"
> If i pass `false` an alert occurs with "false".

@Maqsyo you are right, sorry for a mix up 👍 Changing loader status is kind of the abuse here because `aborted` indicates that uploading was aborted and not errored which is not true in this case.

If you have your own notifications handling, it should listen to `show:*` events which indicates there is notification to show. In this case it will be [`show:warning`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_notification_notification-Notification.html#event-show:warning). As you can see in the docs:

> When this event won't be handled and stopped by event.stop() then data.message of this event will be automatically displayed as system alert.

which means that stopping `show:warning` event will result in alert dialog not showing up. So I think it should be the right approach to integrate with your custom toast-system (it allows you to show different messages depending on the rejection message / error type too).

**Comment by Maqsyo** [comment]
thanks!
